-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Dimension Tables

-- Metal Dimension
CREATE TABLE IF NOT EXISTS dim_metal (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    metal_name TEXT NOT NULL UNIQUE, -- e.g., 'Gold', 'Silver'
    category TEXT -- e.g., 'Precious', 'Industrial' (optional)
);

-- Market Dimension
CREATE TABLE IF NOT EXISTS dim_market (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    market_name TEXT NOT NULL UNIQUE -- e.g., 'Spot', 'MCX', 'LBMA'
);

-- Time Dimension
CREATE TABLE IF NOT EXISTS dim_time (
    id BIGINT PRIMARY KEY, -- Format: YYYYMMDDHH (e.g., 2023102714)
    timestamp TIMESTAMPTZ NOT NULL,
    date DATE NOT NULL,
    day INTEGER NOT NULL,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    hour INTEGER NOT NULL
);

-- Index on timestamp in dim_time for range queries
CREATE INDEX IF NOT EXISTS idx_dim_time_timestamp ON dim_time(timestamp);

-- 2. Fact Table

CREATE TABLE IF NOT EXISTS fact_metal_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metal_id UUID NOT NULL REFERENCES dim_metal(id),
    market_id UUID NOT NULL REFERENCES dim_market(id),
    time_id BIGINT NOT NULL REFERENCES dim_time(id),
    price NUMERIC NOT NULL,
    currency TEXT DEFAULT 'USD',
    unit TEXT, -- e.g., 'oz', 'kg'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Constraint to prevent duplicate entries for the same metal, market, and time
    CONSTRAINT unique_price_entry UNIQUE (metal_id, market_id, time_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_fact_metal_id ON fact_metal_prices(metal_id);
CREATE INDEX IF NOT EXISTS idx_fact_market_id ON fact_metal_prices(market_id);
CREATE INDEX IF NOT EXISTS idx_fact_time_id ON fact_metal_prices(time_id);
-- User specifically asked for "Indexes on timestamp". 
-- Since timestamp is in dim_time, we index time_id here. 
-- We can also add a timestamp column to fact table if strictly needed, 
-- but traditionally it lives in dim_time. 
-- However, for convenience in time-series queries without joining:
-- We'll keep it normalized as per "Ensure schema is normalized" instruction.
